config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todolists
  root "todolists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  validates_presence_of :title, :description, :date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, :only => [:edit, :update, :destroy]
  def index
    @todolists = Todolist.all
  end

  def new
    @todolist = Todolist.new
  end

  def create
    @todolist = Todolist.new(todolist_params)
    # binding.pry
    if @todolist.save
      redirect_to todolists_url
    else
      render :action => :new
    end
  end


  def update
    if @todolist.update(todolist_params)
      # .update(description: 'qwer', title: 'wer32r', date: '132r12f')
      redirect_to todolists_url
    else
      # render action: :edit
      render :action => :edit
    end
  end



  def destroy
    # binding.pry
    @todolist.destroy

    redirect_to todolists_url
  end

  private

  def set_todolist
    @todolist = Todolist.find(params[:id])
  end

  def todolist_params
    # todolist_params = {
    #   todolist:
    # }
    # {
    #     title: '1234145',
    #     description: '1234',
    #     date: '2018-6-1'
    #   }
    # params[:title]
    #
    # {
    #   'title' => '12341234'
    # }
    #
    # params['title']

    params.require(:todolist).permit(:title, :description, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistRor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/_form.html.erb
<% if @todolist.errors.present? %>
  <ul>
    <% @todolist.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize} #{message}" %> </li>
    <% end %>
  </ul>
<% end %>

<div class="form container">
  <%= form_for @todolist do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date, class: "form-control" %>
    </div>
      <%= f.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/todolists/edit.html.erb
<%= render :partial => "form" %>

app/views/todolists/index.html.erb
<div class="container">
  <table class="table table-striped table-condensed ">
   <% @todolists.each do |todolist| %>
     <tr>
       <td><%= todolist.title %></td>
       <td><%= todolist.description %></td>
       <td><%= todolist.date %></td>
       <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
       <td><%= link_to 'Destroy', todolist_path(todolist), method: :delete, data:{ confirm: "Are you sure?" } %></td>
     </tr>
   <% end %>
  </table>
  <%= link_to '+ New Todo', new_todolist_path, class: "badge badge-dark" %>
</div>

app/views/todolists/new.html.erb
<%= render :partial => "form" %>